version: 2
updates:
- package-ecosystem: npm
  directory: "/bot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
