name: website-ci
on:
  pull_request:
    paths:
      - "website/**"
defaults:
  run:
    working-directory: website
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: cp .env.example .env
      - run: npm run lint
